/**
 * controllers/otpController.js — v3 FIXED
 *
 * BUGS FIXED:
 *  1. getOTPStatus used req.params.id but route declares :bookingId → always undefined
 *     Fixed: now uses req.params.bookingId (matches /status/:bookingId route)
 *
 *  2. getBookingForProvider: added try/catch around findById so invalid ObjectIds
 *     return a clean 400 instead of crashing the server with CastError
 *
 *  3. generateOTP: added guard when booking.user is null (edge case for flight bookings
 *     that store no itemModel user ref correctly)
 *
 *  4. verifyOTP: after successful verify, also update otpSent flag and use lean() on
 *     the final booking fetch to prevent accidental double-save
 *
 * SECURITY: OTP can ONLY be generated by admin/vendor.
 *
 * Endpoints:
 *   POST /api/otp/generate      — PROVIDER ONLY: generate + email OTP to user
 *   POST /api/otp/verify        — PROVIDER ONLY: verify OTP, mark booking verified
 *   GET  /api/otp/booking/:id   — PROVIDER: lookup booking details by ID
 *   GET  /api/otp/status/:bookingId — USER: read-only OTP status (note: :bookingId not :id)
 */
const mongoose = require('mongoose');
const Booking  = require('../models/Booking');
const OTP      = require('../models/OTP');
const Hotel    = require('../models/Hotel');
const Bike     = require('../models/Bike');
const Cab      = require('../models/Cab');
const Service  = require('../models/Service');
const Bus      = require('../models/Bus');
const User     = require('../models/User');
const { sendOTPEmail } = require('../utils/emailService');

const OTP_EXPIRY_MIN      = Number(process.env.OTP_EXPIRY_MINUTES) || 10;
const RESEND_COOLDOWN_SEC = 60;

// ── helpers ──────────────────────────────────────────────────────────────────

async function resolveServiceName(booking) {
  try {
    const map   = { Hotel, Bike, Cab, Service, Bus };
    const Model = map[booking.itemModel];
    if (!Model) return 'Your Booking';
    const item = await Model.findById(booking.itemId)
      .select('name busName packageName brand busType from to').lean();
    if (!item) return 'Your Booking';
    if (item.from && item.to) return `${item.busName || 'Bus'} (${item.from} → ${item.to})`;
    return item.name || item.busName || item.packageName || `${item.brand} rental` || 'Your Booking';
  } catch { return 'Your Booking'; }
}

function maskEmail(email) {
  if (!email || !email.includes('@')) return '****@****.com';
  const [local, domain] = email.split('@');
  return local.slice(0, 2) + '****@' + domain;
}

/** Validate a string is a valid MongoDB ObjectId */
function isValidObjectId(id) {
  return mongoose.Types.ObjectId.isValid(id);
}

// ── POST /api/otp/generate — PROVIDER ONLY ───────────────────────────────────
const generateOTP = async (req, res) => {
  try {
    const { bookingId } = req.body;

    // ✅ Guard: bookingId required and must be valid
    if (!bookingId) {
      return res.status(400).json({ message: 'bookingId is required' });
    }
    if (!isValidObjectId(bookingId)) {
      return res.status(400).json({ message: 'Invalid bookingId format' });
    }

    const booking = await Booking.findById(bookingId).lean();
    if (!booking) {
      return res.status(404).json({ message: 'Booking not found' });
    }

    // Only confirmed (or verified — allow re-generate) bookings
    if (!['confirmed', 'verified'].includes(booking.status)) {
      return res.status(400).json({
        message: `Cannot generate OTP for a "${booking.status}" booking. Only confirmed bookings are eligible.`,
      });
    }

    // Resend cooldown check
    const existing = await OTP.findOne({ bookingId });
    if (existing && !existing.isVerified) {
      const secsSince = (Date.now() - new Date(existing.lastSentAt).getTime()) / 1000;
      if (secsSince < RESEND_COOLDOWN_SEC) {
        const wait = Math.ceil(RESEND_COOLDOWN_SEC - secsSince);
        return res.status(429).json({
          message:     `Please wait ${wait}s before generating a new OTP`,
          waitSeconds: wait,
        });
      }
    }

    // Generate OTP + hash
    const plainOTP  = OTP.generateOTP();
    const otpHash   = OTP.hashOTP(plainOTP);
    const expiresAt = new Date(Date.now() + OTP_EXPIRY_MIN * 60 * 1000);

    await OTP.findOneAndUpdate(
      { bookingId },
      { otpHash, expiresAt, isVerified: false, attempts: 0, lastSentAt: new Date() },
      { upsert: true, new: true }
    );
    await Booking.findByIdAndUpdate(bookingId, { otpSent: true });

    // ✅ Guard: fetch user for email — handle missing user gracefully
    if (!booking.user) {
      return res.status(400).json({ message: 'Booking has no associated user' });
    }
    const user = await User.findById(booking.user).select('name email').lean();
    if (!user) {
      return res.status(400).json({ message: 'User account not found for this booking' });
    }
    if (!user.email) {
      return res.status(400).json({ message: 'User email not found — cannot send OTP' });
    }

    const serviceName = await resolveServiceName(booking);

    // Send email (non-blocking — don't fail if email fails, OTP is still valid)
    try {
      await sendOTPEmail({
        to:               user.email,
        name:             user.name,
        otp:              plainOTP,
        bookingId,
        serviceName,
        serviceType:      booking.type,
        expiresInMinutes: OTP_EXPIRY_MIN,
      });
     
    } catch (mailErr) {
      console.error('⚠️  Email delivery failed (OTP still valid):', mailErr.message);
    }

    console.log(`🔐 OTP generated by provider ${req.user.id} for booking ${bookingId}`);

    res.json({
      success:   true,
      message:   `OTP sent to customer's email (${maskEmail(user.email)})`,
      email:     maskEmail(user.email),
      expiresIn: OTP_EXPIRY_MIN * 60,   // seconds
      expiresAt,
      // Dev-only: expose plainOTP in response so devs can test without email
      ...(process.env.NODE_ENV !== 'production' && { devOTP: plainOTP }),
    });
  } catch (err) {
    console.error('generateOTP error:', err);
    res.status(500).json({ message: err.message || 'Internal server error' });
  }
};

// ── POST /api/otp/verify — PROVIDER ONLY ─────────────────────────────────────
const verifyOTP = async (req, res) => {
  try {
    const { bookingId, otp } = req.body;

    if (!bookingId || !otp) {
      return res.status(400).json({ message: 'bookingId and otp are required' });
    }
    if (!isValidObjectId(bookingId)) {
      return res.status(400).json({ message: 'Invalid bookingId format' });
    }

    const otpDoc = await OTP.findOne({ bookingId });
    if (!otpDoc) {
      return res.status(404).json({ message: 'No OTP found for this booking. Please generate one first.' });
    }

    if (otpDoc.isVerified) {
      return res.status(400).json({ message: 'This booking has already been verified.' });
    }

    if (otpDoc.isLocked()) {
      return res.status(429).json({
        message: 'Too many incorrect attempts. Please generate a new OTP.',
        locked:  true,
      });
    }

    if (otpDoc.isExpired()) {
      return res.status(400).json({
        message: 'OTP has expired. Please generate a new one.',
        expired: true,
      });
    }

    // Verify OTP hash
    if (!otpDoc.checkOTP(otp.trim())) {
      otpDoc.attempts += 1;
      await otpDoc.save();
      const remaining = Math.max(0, otpDoc.maxAttempts - otpDoc.attempts);
      return res.status(400).json({
        message:           `Invalid OTP. ${remaining} attempt${remaining !== 1 ? 's' : ''} remaining.`,
        attemptsRemaining: remaining,
      });
    }

    // ✅ OTP correct — mark verified
    otpDoc.isVerified = true;
    await otpDoc.save();

    const booking = await Booking.findByIdAndUpdate(
      bookingId,
      { status: 'verified', verifiedAt: new Date() },
      { new: true }
    ).populate('user', 'name email phone').lean();

    console.log(`✅ Booking ${bookingId} VERIFIED by provider ${req.user?.id}`);

    res.json({
      success: true,
      message: 'Booking verified! Service access granted. ✅',
      booking: {
        _id:         booking._id,
        type:        booking.type,
        status:      booking.status,
        verifiedAt:  booking.verifiedAt,
        startDate:   booking.startDate,
        endDate:     booking.endDate,
        guests:      booking.guests,
        seatsBooked: booking.seatsBooked,
        totalAmount: booking.totalAmount,
        user: {
          name:  booking.user?.name,
          email: booking.user?.email,
          phone: booking.user?.phone,
        },
      },
    });
  } catch (err) {
    console.error('verifyOTP error:', err);
    res.status(500).json({ message: err.message || 'Internal server error' });
  }
};

// ── GET /api/otp/booking/:id — Provider: lookup booking ──────────────────────
const getBookingForProvider = async (req, res) => {
  try {
    const { id } = req.params;

    // ✅ FIX: Validate ObjectId before DB call to prevent CastError crash
    if (!isValidObjectId(id)) {
      return res.status(400).json({ message: 'Invalid Booking ID format. Must be a valid 24-character ID.' });
    }

    const booking = await Booking.findById(id)
      .populate('user', 'name email phone profileImage avatar')
      .lean();
    if (!booking) {
      return res.status(404).json({ message: 'Booking not found. Please check the Booking ID.' });
    }

    // Resolve the service item details
    const map   = { Hotel, Bike, Cab, Service, Bus };
    const Model = map[booking.itemModel];
    let item    = null;
    if (Model) {
      item = await Model.findById(booking.itemId)
        .select('name busName packageName brand image images from to city location').lean();
    }

    const otpDoc = await OTP.findOne({ bookingId: booking._id }).lean();

    res.json({
      success: true,
      booking: {
        ...booking,
        serviceName:     item?.name || item?.busName || item?.packageName || booking.type,
        serviceImage:    item?.images?.[0] || item?.image || null,
        serviceLocation: item?.city || item?.location || (item?.from && item?.to ? `${item.from} → ${item.to}` : null),
      },
      otp: otpDoc ? {
        isVerified:        otpDoc.isVerified,
        isExpired:         new Date() > otpDoc.expiresAt,
        expiresAt:         otpDoc.expiresAt,
        attemptsUsed:      otpDoc.attempts,
        attemptsRemaining: Math.max(0, otpDoc.maxAttempts - otpDoc.attempts),
        canResend:         (Date.now() - new Date(otpDoc.lastSentAt).getTime()) / 1000 > RESEND_COOLDOWN_SEC,
        lastSentAt:        otpDoc.lastSentAt,
      } : null,
    });
  } catch (err) {
    // ✅ Handle Mongoose CastError for invalid ObjectId gracefully
    if (err.name === 'CastError') {
      return res.status(400).json({ message: 'Invalid Booking ID format' });
    }
    console.error('getBookingForProvider error:', err);
    res.status(500).json({ message: err.message || 'Internal server error' });
  }
};

// ── GET /api/otp/status/:bookingId — User: read-only OTP status ──────────────
const getOTPStatus = async (req, res) => {
  try {
    // ✅ BUG FIX #3 (CRITICAL): Route is /status/:bookingId but old code used req.params.id
    // req.params.id was always undefined → Booking.findById(undefined) → CastError / null
    // Fix: use req.params.bookingId to match the route declaration
    const { bookingId } = req.params;

    if (!bookingId) {
      return res.status(400).json({ message: 'Booking ID is required' });
    }
    if (!isValidObjectId(bookingId)) {
      return res.status(400).json({ message: 'Invalid Booking ID format' });
    }

    const booking = await Booking.findById(bookingId).lean();
    if (!booking) {
      return res.status(404).json({ message: 'Booking not found' });
    }

    // Authorization: only the booking owner, admin, or vendor can check status
    if (
      booking.user.toString() !== req.user.id &&
      req.user.role !== 'admin' &&
      req.user.role !== 'vendor'
    ) {
      return res.status(403).json({ message: 'Not authorized to view this booking status' });
    }

    const otpDoc = await OTP.findOne({ bookingId: booking._id }).lean();

    res.json({
      success:    true,
      otpSent:    booking.otpSent || false,
      status:     booking.status,
      verifiedAt: booking.verifiedAt || null,
      otp: otpDoc ? {
        isVerified: otpDoc.isVerified,
        isExpired:  new Date() > otpDoc.expiresAt,
        expiresAt:  otpDoc.expiresAt,
      } : null,
    });
  } catch (err) {
    if (err.name === 'CastError') {
      return res.status(400).json({ message: 'Invalid Booking ID format' });
    }
    console.error('getOTPStatus error:', err);
    res.status(500).json({ message: err.message || 'Internal server error' });
  }
};

module.exports = { generateOTP, verifyOTP, getBookingForProvider, getOTPStatus };
